chore(js version): updating js tools

diff --git a/tools/hooks/pre-commit b/tools/hooks/pre-commit
--- a/tools/hooks/pre-commit
+++ b/tools/hooks/pre-commit
@@ -1,7 +1,8 @@
 #!/bin/sh
 
 npm run test
-if [ $?  ]; then
+if [ $? -neq 0 ]; then
+  echo 'tests failed. Commit aborted.'
   return 2
 fi;
 
